config/routes.rb
Rails.application.routes.draw do


  devise_for :authors
  root to: 'blog/posts#index'

  namespace :authors do
    resources :posts
  end

  scope module: 'blog' do
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable,  :registerable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  scope :most_recent, -> { order(id: :desc) }

  belongs_to :author
  
  def should_generate_new_friendly_id?
    title_changed?
  end

  def display_day_published
    "Published #{created_at.strftime('%-b %-d, %Y')}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  layout 'author'

end

app/controllers/author/posts_controller.rb
module Author
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    # GET /posts
    # GET /posts.json
    def index
      @posts = Post.most_recent
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = Post.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to author_post_path(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to author_post_path(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to author_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.friendly.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        params.require(:post).permit(:title, :body, :description, :banner_image_url)
      end
  end
end

app/controllers/author_controller.rb
class AuthorController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    # GET /posts
    # GET /posts.json
    def index
      @posts = Post.most_recent
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = Post.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.friendly.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        params.require(:post).permit(:title, :body, :description, :banner_image_url)
      end
  end
end

app/controllers/blog/author_controller.rb
class AuthorController < ApplicationController

end

app/controllers/blog/pages_controller.rb
module Blog
  class PagesController < BlogController
    def about

    end

    def contact

    end
  end

end

app/controllers/blog/posts_controller.rb
module Blog
  class PostsController < BlogController

    # GET /posts
    # GET /posts.json
    def index
      @posts = Post.most_recent
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
      @post = Post.friendly.find(params[:id])
    end
  end

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/author/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :banner_image_url %>
    <%= f.text_field :banner_image_url %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :slug %>
    <%= f.text_field :slug %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/author/posts/_post.html.erb
<tr>
  <td><%= link_to post.title, author_post_path(post) %></td>
  <td></td>
  <td><%= link_to 'Edit', edit_author_post_path(post), class: 'btn btn-sm btn-warning' %></td>
  <td><%= link_to 'Remove', author_post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %></td>
</tr>

app/views/author/posts/edit.html.erb
<% provide(:page_title, "Edit #{@post.title}") %>
<% provide(:author, 'active') %>

<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/author/posts/index.html.erb
<% provide(:page_title, 'All Post') %>
<% provide(:author, 'active') %>

 <div class="row">
   <div>
      <%= link_to 'New post', new_author_post_path, class: 'btn btn-primary ntn-lg' %>
   </div>
   <br>
   <table class="table table-striped">
     <tr>
       <th colspan="4">Title</th>
     </tr>
    <%= render @posts %>
   </table>
 </div>

app/views/author/posts/new.html.erb
<% provide(:page_title, 'New Post') %>
<% provide(:author_active, 'active') %>

<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/author/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:author, 'active') %>

<div>
  <%= link_to 'Edit', edit_author_post_path(@post), class: 'btn btn-sm btn-warning' %>
  <%= link_to 'Remove', author_post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
</div>

<div class="row">
  <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-center">
    <h1><%= @post.title %></h1>
    <p><%= @post.display_day_published %></p>
    <%= @post.body %>
  </div>
</div>

app/views/authors/posts/_form.html.erb
<%= form_for(post, url: url) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="row">
  <div class="col-md-4">

        <div class="card">
          <div class="card-block">
            <% if @post.new_record? %>
              <h4 class="card-title">New Post</h4>
            <% else %>
              <h4 class="card-title">
                <b>Edit</b>
                <span class="thin-text"><%= @post.title %></span>
              </h4>
            <% end %>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="field">
                <%= f.label :title %>
                <%= f.text_field :title, class: 'form-control' %>
              </div>

            </li>
            <li class="list-group-item">
              <div class="field">
                <%= f.label :banner_image_url %>
                <%= f.text_field :banner_image_url, class: 'form-control' %>
              </div>
            </li>
            <li class="list-group-item">
              <div class="field">
                <%= f.label :description %>
                <%= f.text_area :description, class: 'form-control' %>
              </div>
            </li>
            <li class="list-group-item">
              <div class="field">
                <div class="actions">
                  <%= f.submit "Save", class: 'btn btn-success btn-block' %>
                </div>
              </div>
            </li>
          </ul>
        </div>

        <% if @post.persisted? %>
          <%= link_to 'Show', @post %>
        <% end %>
          <%= link_to 'Back', authors_posts_path %>

  </div>
  <div class="col-md-8">
    <div class="field">

      <%= f.text_area :body %>
    </div>

  </div>
</div>


<% end %>

app/views/authors/posts/_post.html.erb
<tr>
  <td><%= link_to post.title, authors_post_path(post) %></td>
  <td></td>
  <td><%= link_to 'Edit', edit_authors_post_path(post), class: 'btn btn-sm btn-warning' %></td>
  <td><%= link_to 'Remove', authors_post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %></td>
</tr>

app/views/authors/posts/edit.html.erb
<% provide(:page_title, "Edit #{@post.title}") %>
<% provide(:author, 'active') %>

<%= render 'form', post: @post, url: authors_post_url(@post) %>

<!--
<%= link_to 'Show', @post %> |
<%= link_to 'Back', authors_posts_path %>
-->

app/views/authors/posts/index.html.erb
<% provide(:page_title, 'All Post') %>
<% provide(:author, 'active') %>

 <div class="row">
   <div>
      <%= link_to 'New post', new_authors_post_path, class: 'btn btn-primary ntn-lg' %>
   </div>
   <br>
   <table class="table table-striped">
     <tr>
       <th colspan="4">Title</th>
     </tr>
    <%= render @posts %>
   </table>
 </div>

app/views/authors/posts/new.html.erb
<% provide(:page_title, 'New Post') %>
<% provide(:author_active, 'active') %>

<%= render 'form', post: @post, url: authors_posts_url %>

<!--
<%= link_to 'Back', authors_posts_path %>
-->

app/views/authors/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:author, 'active') %>

<div>
  <%= link_to 'Edit', edit_authors_post_path(@post), class: 'btn btn-sm btn-warning' %>
  <%= link_to 'Remove', authors_post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
</div>

<div class="row">
  <div class="col-md-10 offset-md-1 col-lg-12 offset-lg-2 text-xs-center">
    <h1><%= @post.title %></h1>
    <p><%= @post.display_day_published %></p>
    <%= @post.body.html_safe %>
  </div>
</div>

app/views/blog/pages/about.html.erb
<% provide(:about_active, 'active') %>
<h1>About page</h1>
<div class="">
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div><br>
<div class="">
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div><br>
<div class="">
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div><br>
<div class="">
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div><br>
<div class="">
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div><br>
<div class="">
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div><br>
<div class="">
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div><br>
<div class="">
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div><br>

app/views/blog/pages/contact.html.erb
<% provide(:contact_active, 'active') %>
<div class="">
    <h1>Ubicanos</h1>
</div>

<div class="address">
  <div class="col-sm-12 col-lg-8">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3916.5765130613067!2d-63.87123408468309!3d10.9953032581208!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8c318dd48668b061%3A0x44706c911fed8284!2sUniversidad+de+Oriente+-+Campus+de+Guatamare!5e0!3m2!1sen!2sve!4v1492832659256" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>  </div>
  <div class="col-sm-12 col-lg-4">
    <h3>Venezuela</h3><p>
      Guatamare <br>
      Estado Nueva Esparta<br>
      Universidad de Oriente<br>
      Autopista Porlamar-La Asuncion, 6301, Nueva Esparta<br>
      Tlf. 0295-4006500<br>
      Contacto: <a href="https://www.linkedin.com/in/gregory-mujica-2a0400b6/" target="_blank"><b> Gregory Mujica</b> </a> <img src="https://lh4.googleusercontent.com/-CepHHHB3l1Y/AAAAAAAAAAI/AAAAAAAAUAY/1YtVwgbVuJk/s0-c-k-no-ns/photo.jpg" height="18px" width="18px" alt=""><br>
      Email: gregorymujica1993@gmail.com<br><br>

  </div>
</div>

app/views/blog/posts/_post.html.erb
<div class='col-sm-4 clo-lg-4'>
  <div class="card">
    <div class="card-topper" style='background-image: url(<%= post.banner_image_url %>);'></div>
    <div class="card-block">
      <h4 class="card-title"><%= link_to post.title, post %></h4>
      <p class="published-date"><%= post.display_day_published %></p>
      <p class="card-text"><%= truncate(post.description, length: 130) %></p>
      <%= link_to 'Read', post, class: 'btn btn-read' %>
    </div>
  </div>
</div>

app/views/blog/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:blog_active, 'active') %>

<div class="row">
  <div class="col-md-10 offset-md-1 col-lg-12 offset-lg-2 text-xs-center">
    <h1><%= @post.title %></h1>
    <p><%= @post.display_day_published %></p>
    <%= @post.body.html_safe %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="collapse" id="exCollapsingNavbar">
    <div class="collapse-bg p-a-1">
      <div class='card'>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}" %>
          </li>
          <li class="list-group-item">
            <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
          </li>
          <li class="list-group-item">
            <%= link_to 'Contact', contact_path, class: "nav-link #{yield(:contact_active)}" %>
          </li>
          <% if author_signed_in? %>
            <li class="list-group-item">
              <%= link_to 'My Posts', authors_posts_path, class: "nav-link #{yield(:author)}" %>
            </li>
            <li class="list-group-item">
              <%= link_to 'Logout', destroy_author_session_path, method: :delete, class: "nav-link" %>
             </li>
          <% end %>
        </ul>
      </div>
    </div>
</div>

<nav class="navbar navbar-light bg-faded">
  <div class='container'>
    <a class='navbar-brand', href='/'>
      CIT<span class="light">udone</span>
    </a>
    <button class="navbar-toggler hidden-sm-up pull-xs-right" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
      &#9776;
    </button>
    <ul class="nav navbar-nav  pull-sm-right hidden-xs-down"> <!--navbar-nav -->
      <li class="nav-item">
        <%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Contact', contact_path, class: "nav-link #{yield(:contact_active)}" %>
      <% if author_signed_in? %>
        <li class="nav-item">
          <%= link_to 'My Posts', authors_posts_path, class: "nav-link #{yield(:author)}" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', destroy_author_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% end %>
      </ul>
  </div>
</nav>

app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title)%>| CITudone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//cloud.tinymce.com/stable/tinymce.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% if notice || alert %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>
    <div class="container <%= controller_name %> <%= action_name %>">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title)%>| CITudone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container <%= controller_name %> <%= action_name %>">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :banner_image_url %>
    <%= f.text_field :banner_image_url %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :slug %>
    <%= f.text_field :slug %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class='col-sm-4 clo-lg-4'>
  <div class="card">
    <div class="card-topper" style='background-image: url(<%= post.banner_image_url %>);'></div>
    <div class="card-block">
      <h4 class="card-title"><%= link_to post.title, post %></h4>
      <p class="published-date"><%= post.display_day_published %></p>
      <p class="card-text"><%= truncate(post.description, length: 130) %></p>
      <%= link_to 'Read', post, class: 'btn btn-read' %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% provide(:page_title, 'All Post') %>
<% provide(:blog_active, 'active') %>

 <div class="row">
   <%= render @posts %>
 </div>

app/views/posts/new.html.erb
<% provide(:page_title, 'New Post') %>
<% provide(:blog_active, 'active') %>

<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:blog_active, 'active') %>

<div class="row">
  <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-center">
    <h1><%= @post.title %></h1>
    <p><%= @post.display_day_published %></p>
    <%= @post.body %>
  </div>
</div>